baseURL = "https://nicolevanderhoeven.github.io"
languageCode = "en-us"
title = "Nicole van der Hoeven"
theme = "cactus"
copyright = "Nicole van der Hoeven" # cactus will use title if copyright is not set
disqusShortname = "example" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"


# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog"
weight = 2

[[menu.main]]
name = "Notes"
url = "https://notes.nicolevanderhoeven.com"
weight = 3

[[menu.main]]
name = "Work"
url = "/work"
weight = 4

[[menu.main]]
name = "Speaking"
url = "/speaking"
weight = 5

[[menu.main]]
name = "Gear"
url = "/gear"
weight = 6

[[menu.main]]
name = "Ethics"
url = "/ethics"
weight = 7

[[menu.main]]
name = "Course"
url = "https://courses.nicolevanderhoeven.com/o4e"
weight = 8

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]
  colortheme = "dark" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = true # default

  # Home page settings
  description = "Hi, I'm Nicole van der Hoeven. I'm a Developer Advocate at k6.io (Grafana Labs). I've spent my career making software faster as a performance engineer, but I'm also a YouTuber. I write stuff, film and produce videos, speak at conferences, and otherwise just generally learn in public. This site is a home for everything I'm doing on the interwebs. I currently live between two places: Portugal and the Netherlands."
  mainSection = "blog" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 10 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/gohugoio" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-Jan-02" # default

  # Post page settings
  show_updated = false # default

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "youtube"
    link = "https://youtube.com/nicolevanderhoeven"
  [[params.social]]
    name = "github"
    link = "https://github.com/nicolevanderhoeven"
  [[params.social]]
    name = "mastodon"
    link = "https://pkm.social/@nicole"
  [[params.social]]
    name = "patreon"
    link = "https://patreon.com/nicolevdh"
  [[params.social]]
    name = "email"
    link = "nicole@nicolevanderhoeven.com"  # no need for "mailto:" in the head
  [[params.social]]
    name = "twitter"
    link = "https://twitter.com/n_vanderhoeven"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/nvanderhoeven"
  [[params.social]]
    name = "youtube"
    link = "https://youtube.com/c/luckydippers"
  [[params.social]]
    name = "youtube"
    link = "https://youtube.com/c/k6test"


[related]
    threshold = 0 
    includeNewer = true
    toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100